### PR TITLE
Html env docs

### PR DESCRIPTION
**Pull request by benjgil**
add docs for the html aspect (environment) and add reference to it in the environments section

(not investing in this too much as there's a full docs rework going on, but it's still important to have users know this env exists)

### CODE REVIEW

**Comment by debs-obrien** [comment]
Thanks @benjgil 
@giteden keep this in mind for new docs

**Review by debs-obrien — CHANGES_REQUESTED** [review]
link doesnt seem to be working in preview can you please check it @benjgil 

https://deploy-preview-237--harmony-docs.netlify.app/aspects/html

**Comment by benjgil** [comment]
@debs-obrien 
Fixed (was an issue with the header yaml)

**Comment by debs-obrien** [comment]
great, thanks

**Pull request merged**
